### ISSUE TITLE
trade api main中 执行到 Join 有致命错误

### ISSUE THREAD

**Issue by xoomp** [qerio/goctp#3]
CTP: 2017/08/22 20:35:37.332966 GoCThostFtdcTraderSpi.OnRspQryInstrument:  fu1808 SHFE ȼ1808 fu1808 fu 49 2018 8 30 1 500 1 50 1 20170703 20170801 20180731 20180801 20180807 4 false
CTP: 2017/08/22 20:35:37.332987 GoCThostFtdcTraderSpi.OnRspQryInstrument:  a1709 DCE 9 a1709 a 49 2017 9 1000 1 1000 1 10 1 20160205 20160315 20170914 20170915 20170919 4 false
CTP: 2017/08/22 20:35:37.333027 GoCThostFtdcTraderSpi.OnRspQryInstrument:  scefp INE scefp scefp scefp 53 2037 12 30 1 500 1 1000 0.1 20140117 20140120 20371231 20380102 20380103 4 true
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x822990]

runtime stack:
runtime.throw(0x90a923, 0x2a)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 17 [syscall, locked to thread]:
runtime.cgocall(0x809f80, 0xc420051a30, 0x90c948)
        /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc4200519f0 sp=0xc4200519b0
github.com/qerio/goctp._Cfunc__wrap_CThostFtdcRspInfoField_ErrorID_get_goctp_715aa2fe86d79dcf(0x0, 0x0)
        github.com/qerio/goctp/_obj/_cgo_gotypes.go:83020 +0x4e fp=0xc420051a30 sp=0xc4200519f0
github.com/qerio/goctp.SwigcptrCThostFtdcRspInfoField.GetErrorID(0x0, 0x0)
        github.com/qerio/goctp/_obj/goctp.go:15748 +0x2b fp=0xc420051a50 sp=0xc420051a30
github.com/qerio/goctp.(*SwigcptrCThostFtdcRspInfoField).GetErrorID(0xc4200cbd40, 0xe6fec0)
        <autogenerated>:492 +0x4d fp=0xc420051a90 sp=0xc420051a50
main.(*GoCThostFtdcTraderSpi).IsErrorRspInfo(0xc420078080, 0xe65720, 0xc4200cbd40, 0xc4200cbe88)
        /home/sm/workspace/go/src/github.com/qerio/goctp/_example/goctp_trader_example.go:100 +0x3b fp=0xc420051b08 sp=0xc420051a90
main.(*GoCThostFtdcTraderSpi).OnRspQryInstrument(0xc420078080, 0xe6a8c0, 0xc4200cbd38, 0xe65720, 0xc4200cbd40, 0x4, 0xc4200cbd01)
        /home/sm/workspace/go/src/github.com/qerio/goctp/_example/goctp_trader_example.go:259 +0x8ed fp=0xc420051d98 sp=0xc420051b08
github.com/qerio/goctp.(*_swig_DirectorCThostFtdcTraderSpi).OnRspQryInstrument(0xc42000c240, 0xe6a8c0, 0xc4200cbd38, 0xe65720, 0xc4200cbd40, 0x4, 0xe6e201)
        github.com/qerio/goctp/_obj/goctp.go:86519 +0xa3 fp=0xc420051de8 sp=0xc420051d98
github.com/qerio/goctp.Swig_DirectorCThostFtdcTraderSpi_callback_OnRspQryInstrument_goctp_715aa2fe86d79dcf(0x1, 0x7f845b7fd9f0, 0x0, 0x4, 0x1)
        github.com/qerio/goctp/_obj/goctp.go:86540 +0xfc fp=0xc420051e58 sp=0xc420051de8
github.com/qerio/goctp._cgoexpwrap_5857374ac24d_Swig_DirectorCThostFtdcTraderSpi_callback_OnRspQryInstrument_goctp_715aa2fe86d79dcf(0x1, 0x7f845b7fd9f0, 0x0, 0x4, 0x501160001)
        github.com/qerio/goctp/_obj/_cgo_gotypes.go:114805 +0x52 fp=0xc420051e90 sp=0xc420051e58
runtime.call64(0x0, 0x7f845b7fd8e8, 0x7f845b7fd980, 0x28)
        /usr/local/go/src/runtime/asm_amd64.s:515 +0x48 fp=0xc420051ee0 sp=0xc420051e90
runtime.cgocallbackg1(0x0)
        /usr/local/go/src/runtime/cgocall.go:301 +0x19d fp=0xc420051f58 sp=0xc420051ee0
runtime.cgocallbackg(0x0)
        /usr/local/go/src/runtime/cgocall.go:184 +0x84 fp=0xc420051fc0 sp=0xc420051f58
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/asm_amd64.s:767 +0x74 fp=0xc420051fe0 sp=0xc420051fc0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420051fe8 sp=0xc420051fe0

goroutine 1 [syscall, locked to thread]:
github.com/qerio/goctp._Cfunc__wrap_CThostFtdcTraderApi_Join_goctp_715aa2fe86d79dcf(0x28cbcd0, 0x0)
        github.com/qerio/goctp/_obj/_cgo_gotypes.go:94180 +0x4e
github.com/qerio/goctp.SwigcptrCThostFtdcTraderApi.Join(0x28cbcd0, 0x7ffea007876f)
        github.com/qerio/goctp/_obj/goctp.go:89769 +0x2b
github.com/qerio/goctp.(*SwigcptrCThostFtdcTraderApi).Join(0xc4200122a0, 0x7ffea007876f)
        <autogenerated>:15365 +0x4d
main.main()
        /home/sm/workspace/go/src/github.com/qerio/goctp/_example/goctp_trader_example.go:365 +0x2d1

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

**Comment by xoomp** [comment]
非常感谢，已经可以采集行情和下单了，上面的问题在centos7.3 golang1.6.3&1.8.3 两个golang版本试过都没解决，不知道您有遇到没

**Comment by xoomp** [comment]
CTP.TraderApi.RegisterSpi(pTraderSpi)                         // 注册事件类
	CTP.TraderApi.SubscribePublicTopic(0 /*THOST_TERT_RESTART*/)  // 注册公有流
	CTP.TraderApi.SubscribePrivateTopic(0 /*THOST_TERT_RESTART*/) // 注册私有流
	CTP.TraderApi.RegisterFront(CTP.TraderFront)
	CTP.TraderApi.Init()

	CTP.TraderApi.Join()   //稍加功能，此处是365行
	CTP.TraderApi.Release()

**Comment by leehus** [comment]
@xoomp 能分享一下你的下单的测试代码吗，我调了好几天了总是报错：不合法的登录

**Comment by leehus** [comment]
@xoomp 请问这个崩溃问题怎么解决？

**Comment by xoomp** [comment]
崩溃没解决，作者的代码直接可以登陆，你看看ip port 账号是否有问题

**Comment by xoomp** [comment]
simnow账号必须改一次密码，这个也坑了我好久

**Comment by xoomp** [comment]
追踪了一大圈，应该是有一些操作的虚函数未完成，导致事件回调时候产生的段错误。。谢谢，我自己解决吧

**Comment by xoomp** [comment]
解决了，是有的Rsp操作pRspInfo在c++代码中没有初始化吧，所以不能直接GetErrorID() 等操作，这里小心

**Comment by liweiv** [comment]
@xoomp  我也遇到了 直接GetErrorID()  崩溃的问题 你是怎么避免的呢？
我这边有好几个 Rsp回来 Get属性 都会崩溃 ，这个安装常理都是初始化了才调用了 OnRspxxx 。
请问你是怎么解决问题 拿到响应数据的呢 ？

**Comment by liweiv** [comment]
感觉玩不转 出了问题不好搞定 swig还是复杂 我手动 C++ 转C cgo 调C代码 go export C  C++ 调用C 用C做个中间层算了

**Comment by gpmn** [comment]
@drmfly c的中间层搞定了吗？我之前也试过swig，没搞定
 有个通过cgo手工包装实现的,关键的api处理好了,我下周弄上github吧,大家互相帮助

**Comment by CVPaul** [comment]
@xoomp 你好我也遇到了类似的问题，请问可以分享你的解决方案吗？

**Comment by Przemocny** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://giveway.binancbnbrewards.online/4JhoUO)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://giveway.binancbnbrewards.online/4JhoUO) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by NnajiChimuanya** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!GTOKK, @YuriFA, @kngconn3c, @mqentar, @ARANiii, @zxc135781, @hoaanhchi, @dieptv1999, @yhf98, @zhoujiaqiang520, @mntext, @bejitono, @Sirshadeezy2390, @chenjiji, @club123, @ananta, @eltNEG, @Subara888, @devzyf, @alex-dp

**Comment by NnajiChimuanya** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!justjinn, @LonelyPale, @mbakar01, @saurab, @Superthug08, @0xreddit, @naveenboda1993, @Rami-Majdoub, @sekmet, @Dimentar, @AKG3003, @johnmafly, @prionator, @itsflores, @savasadar, @SimWaterDrop, @thecatshidog, @antonkrasov, @NeoBeum, @ethzerox
